gtfs:
  static:
    chunks: 100
    files:
      agency:
        file: agency.txt
      route:
        file: routes.txt
      stop:
        file: stops.txt
      calendar:
        file: calendar.txt
      trip:
        file: trips.txt
      stoptime:
        file: stop_times.txt