spring:
  datasource:
    dataSourceClassName: org.postgresql.Driver
    platform: postgresql
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
  liquibase:
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}