spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    initialization-mode: ALWAYS
    datasource:
      username: sa
      url: jdbc:h2:mem:staticgtfs;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS STATICGTFS
      driverClassName: org.h2.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: false