spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    initialization-mode: ALWAYS
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none