spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    initialization-mode: ALWAYS
    datasource:
      username: sa
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none