spring:
  datasource:
    dataSourceClassName: org.postgresql.Driver
    platform: postgresql
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none