apiVersion: v1
kind: Service
metadata:
  name: {{ include "staticgtfs.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http }}
      targetPort: {{ .Values.service.http }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.probe }}
      targetPort: {{ .Values.service.probe }}
      protocol: TCP
      name: probe
  selector:
    app: {{ include "staticgtfs.name" . }}
